---
- name: Install podman EL9
  ansible.builtin.dnf:
    name: ['podman.x86_64', 'podman-plugins.x86_64']
    state: present
    enablerepo: "epel"
    disablerepo: "UMD*"
  when: ansible_facts[ 'distribution' ] == 'AlmaLinux' and ansible_facts[ 'distribution_major_version' ] == '9'
  tags: packages

- name: Install podman Fedora
  ansible.builtin.dnf:
    name: ['podman.x86_64', 'podman-plugins.x86_64']
    state: present
  when: ansible_facts[ 'distribution' ] == 'Fedora'
  tags: packages
